export const HandleClick = 'handlePullRequestClick'
export const HandleBlur = 'handlePullRequestBlur'
export const HandleFocus = 'handlePullRequestFocus'
export const HandleInput = 'handlePullRequestFilterInput'
export const HandleSelection = 'handlePullRequestSelection'
export const HandleCreateInput = 'handleCreateInput'
