import { expect, test } from '@jest/globals'
import type { ExplorerState } from '../src/parts/ExplorerState/ExplorerState.ts'
import { createDefaultState } from '../src/parts/CreateDefaultState/CreateDefaultState.ts'
import { getIndexFromPosition } from '../src/parts/GetIndexFromPosition/GetIndexFromPosition.ts'

test('getIndexFromPosition', () => {
  const state: ExplorerState = {
    ...createDefaultState(),
    confirmDelete: false,
    confirmPaste: false,
    cutItems: [],
    deltaY: 0,
    dropTargets: [],
    editingErrorMessage: '',
    editingIcon: '',
    editingIndex: -1,
    editingSelectionEnd: 0,
    editingSelectionStart: 0,
    editingType: 0,
    editingValue: '',
    excluded: [],
    fileIconCache: {
      'test:///virtual-dom/.git': 'test://file-icons/folder_type_git.svg',
      'test:///virtual-dom/.git/branches': 'test://file-icons/default_folder.svg',
      'test:///virtual-dom/.git/COMMIT_EDITMSG': 'test://file-icons/default_file.svg',
      'test:///virtual-dom/.git/config': 'test://file-icons/default_file.svg',
      'test:///virtual-dom/.git/description': 'test://file-icons/default_file.svg',
      'test:///virtual-dom/.git/FETCH_HEAD': 'test://file-icons/default_file.svg',
      'test:///virtual-dom/.git/HEAD': 'test://file-icons/default_file.svg',
      'test:///virtual-dom/.git/hooks': 'test://file-icons/folder_type_hook.svg',
      'test:///virtual-dom/.git/index': 'test://file-icons/default_file.svg',
      'test:///virtual-dom/.git/info': 'test://file-icons/default_folder.svg',
      'test:///virtual-dom/.git/logs': 'test://file-icons/folder_type_log.svg',
      'test:///virtual-dom/.git/objects': 'test://file-icons/default_folder.svg',
      'test:///virtual-dom/.git/ORIG_HEAD': 'test://file-icons/default_file.svg',
      'test:///virtual-dom/.git/packed-refs': 'test://file-icons/default_file.svg',
      'test:///virtual-dom/.git/refs': 'test://file-icons/default_folder.svg',
      'test:///virtual-dom/.git/rr-cache': 'test://file-icons/default_folder.svg',
      'test:///virtual-dom/.github': 'test://file-icons/folder_type_github.svg',
      'test:///virtual-dom/.gitignore': 'test://file-icons/file_type_git.svg',
      'test:///virtual-dom/.gitpod.Dockerfile': 'test://file-icons/file_type_docker.svg',
      'test:///virtual-dom/.gitpod.yml': 'test://file-icons/file_type_gitpod.svg',
      'test:///virtual-dom/.nvmrc': 'test://file-icons/file_type_node.svg',
      'test:///virtual-dom/.vscode': 'test://file-icons/folder_type_vscode.svg',
      'test:///virtual-dom/dist': 'test://file-icons/folder_type_dist.svg',
      'test:///virtual-dom/eslint.config.js': 'test://file-icons/file_type_eslint.svg',
      'test:///virtual-dom/lerna.json': 'test://file-icons/file_type_lerna.svg',
      'test:///virtual-dom/LICENSE': 'test://file-icons/file_type_license.svg',
      'test:///virtual-dom/node_modules': 'test://file-icons/folder_type_node.svg',
      'test:///virtual-dom/package-lock.json': 'test://file-icons/file_type_npm.svg',
      'test:///virtual-dom/package.json': 'test://file-icons/file_type_npm.svg',
      'test:///virtual-dom/packages': 'test://file-icons/folder_type_package.svg',
      'test:///virtual-dom/README.md': 'test://file-icons/file_type_markdown.svg',
      'test:///virtual-dom/scripts': 'test://file-icons/folder_type_script.svg',
      'test:///virtual-dom/tsconfig.json': 'test://file-icons/file_type_tsconfig.svg',
      'test:///virtual-dom/virtual-dom-worker': 'test://file-icons/default_folder.svg',
    },
    finalDeltaY: 0,
    focus: 0,
    focused: false,
    focusedIndex: 0,
    focusWord: '',
    focusWordTimeout: 800,
    handleOffset: 0,
    height: 964,
    hoverIndex: -1,
    icons: [
      'test://file-icons/folder_type_git.svg',
      'test://file-icons/folder_type_github.svg',
      'test://file-icons/folder_type_vscode.svg',
      'test://file-icons/folder_type_dist.svg',
      'test://file-icons/folder_type_node.svg',
      'test://file-icons/folder_type_package.svg',
      'test://file-icons/folder_type_script.svg',
      'test://file-icons/default_folder.svg',
      'test://file-icons/file_type_git.svg',
      'test://file-icons/file_type_docker.svg',
      'test://file-icons/file_type_gitpod.svg',
      'test://file-icons/file_type_node.svg',
      'test://file-icons/file_type_license.svg',
      'test://file-icons/file_type_markdown.svg',
      'test://file-icons/file_type_eslint.svg',
      'test://file-icons/file_type_lerna.svg',
      'test://file-icons/file_type_npm.svg',
      'test://file-icons/file_type_npm.svg',
      'test://file-icons/file_type_tsconfig.svg',
    ],
    inputSource: 0,
    isPointerDown: false,
    itemHeight: 22,
    items: [
      {
        depth: 1,
        icon: '',
        name: '.git',
        path: 'test:///virtual-dom/.git',
        posInSet: 1,
        selected: false,
        setSize: 19,
        type: 3,
      },
      {
        depth: 1,
        icon: '',
        name: '.github',
        path: 'test:///virtual-dom/.github',
        posInSet: 2,
        selected: false,
        setSize: 19,
        type: 3,
      },
      {
        depth: 1,
        icon: '',
        name: '.vscode',
        path: 'test:///virtual-dom/.vscode',
        posInSet: 3,
        selected: false,
        setSize: 19,
        type: 3,
      },
      {
        depth: 1,
        icon: '',
        name: 'dist',
        path: 'test:///virtual-dom/dist',
        posInSet: 4,
        selected: false,
        setSize: 19,
        type: 3,
      },
      {
        depth: 1,
        icon: '',
        name: 'node_modules',
        path: 'test:///virtual-dom/node_modules',
        posInSet: 5,
        selected: false,
        setSize: 19,
        type: 3,
      },
      {
        depth: 1,
        icon: '',
        name: 'packages',
        path: 'test:///virtual-dom/packages',
        posInSet: 6,
        selected: false,
        setSize: 19,
        type: 3,
      },
      {
        depth: 1,
        icon: '',
        name: 'scripts',
        path: 'test:///virtual-dom/scripts',
        posInSet: 7,
        selected: false,
        setSize: 19,
        type: 3,
      },
      {
        depth: 1,
        icon: '',
        name: 'virtual-dom-worker',
        path: 'test:///virtual-dom/virtual-dom-worker',
        posInSet: 8,
        selected: false,
        setSize: 19,
        type: 3,
      },
      {
        depth: 1,
        icon: '',
        name: '.gitignore',
        path: 'test:///virtual-dom/.gitignore',
        posInSet: 9,
        selected: false,
        setSize: 19,
        type: 7,
      },
      {
        depth: 1,
        icon: '',
        name: '.gitpod.Dockerfile',
        path: 'test:///virtual-dom/.gitpod.Dockerfile',
        posInSet: 10,
        selected: false,
        setSize: 19,
        type: 7,
      },
      {
        depth: 1,
        icon: '',
        name: '.gitpod.yml',
        path: 'test:///virtual-dom/.gitpod.yml',
        posInSet: 11,
        selected: false,
        setSize: 19,
        type: 7,
      },
      {
        depth: 1,
        icon: '',
        name: '.nvmrc',
        path: 'test:///virtual-dom/.nvmrc',
        posInSet: 12,
        selected: false,
        setSize: 19,
        type: 7,
      },
      {
        depth: 1,
        icon: '',
        name: 'LICENSE',
        path: 'test:///virtual-dom/LICENSE',
        posInSet: 13,
        selected: false,
        setSize: 19,
        type: 7,
      },
      {
        depth: 1,
        icon: '',
        name: 'README.md',
        path: 'test:///virtual-dom/README.md',
        posInSet: 14,
        selected: false,
        setSize: 19,
        type: 7,
      },
      {
        depth: 1,
        icon: '',
        name: 'eslint.config.js',
        path: 'test:///virtual-dom/eslint.config.js',
        posInSet: 15,
        selected: false,
        setSize: 19,
        type: 7,
      },
      {
        depth: 1,
        icon: '',
        name: 'lerna.json',
        path: 'test:///virtual-dom/lerna.json',
        posInSet: 16,
        selected: false,
        setSize: 19,
        type: 7,
      },
      {
        depth: 1,
        icon: '',
        name: 'package-lock.json',
        path: 'test:///virtual-dom/package-lock.json',
        posInSet: 17,
        selected: false,
        setSize: 19,
        type: 7,
      },
      {
        depth: 1,
        icon: '',
        name: 'package.json',
        path: 'test:///virtual-dom/package.json',
        posInSet: 18,
        selected: false,
        setSize: 19,
        type: 7,
      },
      {
        depth: 1,
        icon: '',
        name: 'tsconfig.json',
        path: 'test:///virtual-dom/tsconfig.json',
        posInSet: 19,
        selected: false,
        setSize: 19,
        type: 7,
      },
    ],
    maxLineY: 19,
    minLineY: 0,
    parentUid: 43,
    pasteShouldMove: false,
    pathSeparator: '/',
    platform: 2,
    pointerDownIndex: -1,
    root: 'test:///virtual-dom',
    scrollBarActive: false,
    scrollBarHeight: 0,
    sourceControlIgnoredUris: [],
    uid: 44,
    useChevrons: true,
    version: 0,
    width: 170,
    x: 29,
    y: 1671,
  }
  expect(getIndexFromPosition(state, 988, 1700)).toBe(1)
})
