import type { ExplorerState } from '../ExplorerState/ExplorerState.ts'
import * as ExplorerEditingType from '../ExplorerEditingType/ExplorerEditingType.ts'
import * as ExplorerStates from '../ExplorerStates/ExplorerStates.ts'
import * as Height from '../Height/Height.ts'
import * as PathSeparatorType from '../PathSeparatorType/PathSeparatorType.ts'

// TODO parentUid might ot be needed
export const create = (
  id: number,
  uri: string,
  x: number,
  y: number,
  width: number,
  height: number,
  args: any,
  parentUid: any,
  platform: number = 0,
  assetDir: string = '',
): any => {
  const state: ExplorerState = {
    assetDir,
    compareSourceUri: '',
    confirmDelete: false,
    confirmPaste: false,
    cutItems: [],
    decorations: [],
    deltaY: 0,
    dropTargets: [],
    editingErrorMessage: '',
    editingIcon: '',
    editingIndex: -1,
    editingSelectionEnd: 0,
    editingSelectionStart: 0,
    editingType: ExplorerEditingType.None,
    editingValue: '',
    errorCode: '',
    errorMessage: '',
    errorMessageLeft: 0,
    errorMessageTop: 0,
    errorMessageWidth: 0,
    excluded: [],
    fileIconCache: Object.create(null),
    finalDeltaY: 0,
    focus: 0,
    focused: false,
    focusedIndex: -1,
    focusWord: '',
    focusWordTimeout: 800,
    handleOffset: 0,
    hasError: false,
    height,
    hoverIndex: -1,
    icons: [],
    initial: true,
    inputSource: 0,
    isPointerDown: false,
    itemHeight: Height.ListItem,
    items: [],
    maxIndent: 0,
    maxLineY: 0,
    minLineY: 0,
    parentUid,
    pasteShouldMove: false,
    pathSeparator: PathSeparatorType.Slash,
    platform,
    pointerDownIndex: -1,
    root: '',
    scrollBarActive: false,
    scrollBarHeight: 0,
    sourceControlDecorations: false,
    sourceControlIgnoredUris: [],
    uid: id,
    useChevrons: false,
    version: 0,
    visibleExplorerItems: [],
    width,
    x,
    y,
  }
  ExplorerStates.set(state.uid, state, state)
  return state
}
